<script setup lang="ts">
/**
 * DagDiagram — embeds a rendered DAG diagram from the auto-generated
 * `docs/architecture/dags/<name>.md` files. The file is generated by
 * `scripts/render-dags.ts` via dagonizer's `MermaidRenderer.render(dag)`,
 * so the rendered topology always matches what the dispatcher executes.
 *
 * Usage in a markdown page:
 *
 * ```html
 * <DagDiagram name="squashage-record" />
 * <DagDiagram name="squashage-run" />
 * ```
 *
 * Markdown content of the source file is included via `<<<` import-syntax
 * in the page that hosts it; this component is a thin wrapper that adds a
 * caption + responsive container.
 */
defineProps<{
  /** File stem under `docs/architecture/dags/`. */
  name: string;
  /** Optional caption shown below the diagram. */
  caption?: string;
}>();
</script>

<template>
  <figure class="dag-diagram">
    <div class="dag-diagram__viewport">
      <slot />
    </div>
    <figcaption v-if="caption" class="dag-diagram__caption">
      {{ caption }} <span class="dag-diagram__source">(rendered from <code>squashage:{{ name.replace('squashage-', '') }}</code> via dagonizer)</span>
    </figcaption>
  </figure>
</template>

<style scoped>
.dag-diagram {
  margin: 1.5rem 0;
  padding: 0;
}
.dag-diagram__viewport {
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
  padding: 1rem;
  background: var(--vp-c-bg-soft);
  overflow-x: auto;
}
.dag-diagram__viewport :deep(.mermaid) {
  display: flex;
  justify-content: center;
}
.dag-diagram__caption {
  font-size: 0.875rem;
  color: var(--vp-c-text-2);
  margin-top: 0.5rem;
  text-align: center;
}
.dag-diagram__source {
  font-size: 0.75rem;
  opacity: 0.75;
}
</style>
